config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "works#index"
  resources :works
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :work
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @works = Work.where(user_id: current_user.id).order("updated_at DESC")
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.where(user_id: current_user.id).order("updated_at DESC").limit(3)
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <footer class="footer">
      <ul class="nav">
        <% if user_signed_in? %>
          <li class="nav__list">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn" %>
          </li>
        <% else %>
          <li class="nav__list">
            <%= link_to "ログイン", user_session_path, class: "btn" %>
          </li>
          <li class="nav__list">
            <%= link_to "新規登録", new_user_registration_path, class: "btn" %>
          </li>
        <% end %>
      </ul>
    </footer>
  </body>
</html>

app/views/works/_item.erb
<div class= "container__item">
  <div class= "container__item--image">
  </div>
  <h2 class= "container__item--title"><%= work.title%></h2>
  <%= link_to "詳細を見る", work_path(work.id), class: "container__item--btn" %>
  <p class="container__item--date"><span class="bold">作成日時 </span><%= work.created_at %></p>
</div>

app/views/works/index.erb
<header class= "header">
  <h1 class= "header__name"><%= current_user.name %>のポートフォリオ(最新<%= @works.length %>件)</h1>
</header>
<div class= "container">
  <% @works.each do |work| %>
    <%= render partial: "item", locals: {work: work} %>
  <% end %>

    <%= link_to "全ての作品へ", user_path(current_user.id), class: "link" %>

</div>